version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=LaGuacaBarBDA
      - POSTGRES_USER=LaguacaRoot
      - POSTGRES_PASSWORD=nUSIL_/SD32@__dhue
    ports:
      - 5432:5432
    volumes:
      - ./api/postgres_data:/var/lib/postgressql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin.colombia@laguaca.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

